server:
  port: 0

proxy:
  use-proxy: false
  group-names: toast2.japan.pub
  oxylabs:
    use: false
    username: epopcon
    password: FChB5uEd45
    key: 4b33bfee-80a6-11eb-927e-901b0ec4424b
  luminati:
    use: true
    username: lum-customer-epopcon-zone-zone1
    password: jhwfsy8ucuh2
    port: 22225